from .categoryList import CategoryList
from .categoryDetail import CategoryDetail
from .productList import ProductList
from .productDetail import ProductDetail
from .customerList import CustomerList
from .customerDetail import CustomerDetail
from .orderList import OrderList
from .orderDetail import OrderDetail
from .customer_login import customer_login
from .customer_register import customer_register
from .customer_order import customer_order
