# Generated by Django 4.2.1 on 2023-06-17 06:19

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('name_for_site', models.CharField(default='', max_length=50, verbose_name='Название для сайта')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, verbose_name='Показывать на сайте')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='shop.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#6AA9FF', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('phone_wa', models.CharField(max_length=12, verbose_name='Телефон для WA')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый ящик')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('working_time', models.CharField(max_length=100, verbose_name='Время работы')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='LandingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_right', models.ImageField(upload_to='', verbose_name='Изображение справа')),
                ('image_left', models.ImageField(upload_to='', verbose_name='Изображение слева')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Посадочный слайд',
                'verbose_name_plural': 'Посадочный слайд',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('name_for_site', models.CharField(max_length=100, verbose_name='Название для сайта')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена со скидкой')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('show_on_site', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, verbose_name='Показывать на сайте')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5, verbose_name='Российский размер')),
                ('manufacturer_name', models.CharField(max_length=3, verbose_name='Размер производителя')),
                ('bust', models.CharField(max_length=7, verbose_name='Обхват груди, см')),
                ('waist', models.CharField(max_length=7, verbose_name='Обхват талии, см')),
                ('hips', models.CharField(max_length=7, verbose_name='Обхват бёдер, см')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='SocialNets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.contacts', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='shop.product')),
            ],
            options={
                'verbose_name': 'Рейтинг продукта',
                'verbose_name_plural': 'Рейтинг продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fitting_sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='fitting', to='shop.size', verbose_name='Размеры на примерке'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_colors', to='shop.color', verbose_name='Другие цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes', to='shop.size', verbose_name='Размеры'),
        ),
        migrations.CreateModel(
            name='PhotosForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='', verbose_name='Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_imgs', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_color', to='shop.color', verbose_name='Цвет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product', verbose_name='Товар')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='shop.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Заказанный товар',
                'verbose_name_plural': 'Заказанные товары',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('default_address', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
            options={
                'verbose_name': 'Адрес пользователя',
                'verbose_name_plural': 'Адреса пользователей',
            },
        ),
    ]
