# Generated by Django 4.2.1 on 2023-06-18 12:10

from django.db import migrations, models
import shop.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_options_order_cart_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма скидок'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=shop.models.order.Order.number, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=10, verbose_name='Способ получения'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Итоговая сумма заказа'),
        ),
    ]
