# Generated by Django 4.2.1 on 2023-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_comment_order_discount_sum_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='Cумма с учётом скидок'),
        ),
    ]
