# Generated by Django 4.2.1 on 2023-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='Самовывоз', max_length=10, verbose_name='Способ получения'),
        ),
    ]
