from .categoryListSerializer import CategoryListSerializer
from .categoryDetailSerializer import CategoryDetailSerializer
from .productListSerializer import ProductListSerializer
from .productDetailSerializer import ProductDetailSerializer
from .customerListSerializer import CustomerListSerializer
from .customerDetailSerializer import CustomerDetailSerializer
from .orderListSerializer import OrderListSerializer
from .orderDetailSerializer import OrderDetailSerializer
